### ISSUE TITLE
building fungi models

### ISSUE THREAD

**Issue by Rotembartuv** [cdanielmachado/yeast_36_strains#1]
Hi Daniel,

I found your git at one of the issues in CarvMe git.
I'm currently working with prokaryotic models built using CarvMe, and Im trying to build GEM of Penicillium. I tried RAVEN, but they are using a different database than BIGG, and I prefer the CarvMe models.
I have some questions:
1. do you believe that one of the yeast strains here can be used as a reference model in CarvMe?
2. do you think that the notebook here can be modified and fit for fungi models?

Tnx

**Comment by cdanielmachado** [comment]
Hi,

Unfortunately we still don't have a good eukaryotic template model for CarveMe. The yeast models in this repository are quite old and I would not recommend using them either. 

I think that for your specific case, either using RAVEN or just doing a manual reconstruction is the best option.

Best regards,
Daniel
